name: Auto Update Cursor Snap

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour
  workflow_dispatch:      # Allow manual trigger

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      x64_version: ${{ steps.x64_version.outputs.version }}
      x64_url: ${{ steps.x64_version.outputs.url }}
      arm64_version: ${{ steps.arm64_version.outputs.version }}
      arm64_url: ${{ steps.arm64_version.outputs.url }}
      should_update: ${{ steps.check_update.outputs.should_update }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest x64 version
        id: x64_version
        run: |
          DOWNLOAD_URL="https://www.cursor.com/api/download?platform=linux-x64&releaseTrack=latest"
          echo "Checking download URL: $DOWNLOAD_URL"
          
          # Get the JSON response from the API
          API_RESPONSE=$(curl -s "$DOWNLOAD_URL")
          
          # Extract the downloadUrl from the JSON response
          REDIRECT_URL=$(echo "$API_RESPONSE" | grep -o '"downloadUrl":"[^"]*"' | sed 's/"downloadUrl":"//;s/"//')
          
          # Check if REDIRECT_URL is empty
          if [ -z "$REDIRECT_URL" ]; then
            REDIRECT_URL="https://downloads.cursor.com/production/client/linux/x64/appimage/Cursor-0.47.4-8f8a2000673d2c48f6cac5eea2f3f9f2ed5e4ec2.deb.glibc2.28-x86_64.AppImage"
            VERSION="0.47.4"
          else
            # Try to extract version from URL with different patterns
            VERSION=$(echo "$REDIRECT_URL" | grep -oP 'Cursor-\K[^-]+(?=-)' || echo "")
            
            # If the first pattern fails, try an alternative pattern
            if [ -z "$VERSION" ]; then
              VERSION=$(echo "$REDIRECT_URL" | grep -oP 'Cursor-\K[\d\.]+' || echo "0.47.4")
            fi
          fi
          
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "url=$REDIRECT_URL" >> $GITHUB_OUTPUT
          echo "X64 Version: $VERSION"
          echo "X64 URL: $REDIRECT_URL"

      - name: Get latest arm64 version
        id: arm64_version
        run: |
          DOWNLOAD_URL="https://www.cursor.com/api/download?platform=linux-arm64&releaseTrack=latest"
          echo "Checking download URL: $DOWNLOAD_URL"
          
          # Get the JSON response from the API
          API_RESPONSE=$(curl -s "$DOWNLOAD_URL")
          
          # Extract the downloadUrl from the JSON response
          REDIRECT_URL=$(echo "$API_RESPONSE" | grep -o '"downloadUrl":"[^"]*"' | sed 's/"downloadUrl":"//;s/"//')
          
          # Check if REDIRECT_URL is empty
          if [ -z "$REDIRECT_URL" ]; then
            REDIRECT_URL="https://downloads.cursor.com/production/client/linux/arm64/appimage/Cursor-0.47.4-8f8a2000673d2c48f6cac5eea2f3f9f2ed5e4ec2.deb.glibc2.28-aarch64.AppImage"
            VERSION="0.47.4"
          else
            # Try to extract version from URL with different patterns
            VERSION=$(echo "$REDIRECT_URL" | grep -oP 'Cursor-\K[^-]+(?=-)' || echo "")
            
            # If the first pattern fails, try an alternative pattern
            if [ -z "$VERSION" ]; then
              VERSION=$(echo "$REDIRECT_URL" | grep -oP 'Cursor-\K[\d\.]+' || echo "0.47.4")
            fi
          fi
          
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "url=$REDIRECT_URL" >> $GITHUB_OUTPUT
          echo "ARM64 Version: $VERSION"
          echo "ARM64 URL: $REDIRECT_URL"

      - name: Check if update is needed
        id: check_update
        run: |
          # Get current version from README
          CURRENT_VERSION=$(grep -oP 'Latest version: \K.*' README.md || echo "0.0.0")
          echo "Current version: $CURRENT_VERSION"
          echo "New version: ${{ steps.x64_version.outputs.version }}"
          
          # Compare versions
          if [ "$CURRENT_VERSION" != "${{ steps.x64_version.outputs.version }}" ]; then
            echo "should_update=true" >> $GITHUB_OUTPUT
            echo "Update needed: Current=$CURRENT_VERSION, New=${{ steps.x64_version.outputs.version }}"
          else
            echo "should_update=false" >> $GITHUB_OUTPUT
            echo "No update needed: Current version is already $CURRENT_VERSION"
          fi

  build-and-release:
    needs: check-version
    if: needs.check-version.outputs.should_update == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    strategy:
      matrix:
        platform: [linux-x64, linux-arm64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          if [ "${{ matrix.platform }}" == "linux-x64" ]; then
            echo "CURSOR_VERSION=${{ needs.check-version.outputs.x64_version }}" >> $GITHUB_ENV
            echo "DOWNLOAD_URL=${{ needs.check-version.outputs.x64_url }}" >> $GITHUB_ENV
          else
            echo "CURSOR_VERSION=${{ needs.check-version.outputs.arm64_version }}" >> $GITHUB_ENV
            echo "DOWNLOAD_URL=${{ needs.check-version.outputs.arm64_url }}" >> $GITHUB_ENV
          fi

      - name: Install Snapcraft
        run: |
          sudo snap install snapcraft --classic

      - name: Create snapcraft.yaml
        run: |
          # Create snapcraft.yaml with the correct version and URL
          cat > snap/snapcraft.yaml << EOF
          name: cursor-ide
          base: core22
          version: '${{ env.CURSOR_VERSION }}'
          summary: Modern IDE powered by AI
          description: |
            Cursor is a modern IDE powered by AI, designed to help developers write, 
            understand and debug code faster. It features AI-powered code completion, 
            refactoring, and explanation capabilities.

          grade: stable
          confinement: strict

          apps:
            cursor-ide:
              command: bin/cursor
              extensions: [gnome]
              plugs:
                - desktop
                - desktop-legacy
                - wayland
                - x11
                - home
                - network
                - browser-support
                - unity7
                - opengl
                - audio-playback

          parts:
            cursor-ide:
              plugin: dump
              source: ${{ env.DOWNLOAD_URL }}
              source-type: file
              override-build: |
                craftctl default
                mkdir -p \$SNAPCRAFT_PART_INSTALL/bin/
                # Copy the downloaded AppImage with the correct name
                cp \$SNAPCRAFT_PART_SRC/* \$SNAPCRAFT_PART_INSTALL/bin/cursor
                chmod +x \$SNAPCRAFT_PART_INSTALL/bin/cursor
          EOF
          
          # Show the updated snapcraft.yaml for debugging
          echo "Created snapcraft.yaml:"
          cat snap/snapcraft.yaml

      - name: Build Snap
        run: |
          # Build the snap package
          sudo SNAPCRAFT_BUILD_ENVIRONMENT=host snapcraft
          
          # Rename the snap file to include the platform
          if [ -f "cursor-ide_${{ env.CURSOR_VERSION }}_amd64.snap" ]; then
            mv cursor-ide_${{ env.CURSOR_VERSION }}_amd64.snap cursor-ide_${{ env.CURSOR_VERSION }}_${{ matrix.platform }}.snap
          fi

      - name: Upload Snap Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cursor-ide-snap-${{ matrix.platform }}
          path: cursor-ide*.snap
          retention-days: 1

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ env.CURSOR_VERSION }}-${{ matrix.platform }}
          name: Cursor IDE Snap ${{ env.CURSOR_VERSION }} (${{ matrix.platform }})
          files: cursor-ide*.snap
          draft: false
          fail_on_unmatched_files: false
          prerelease: false

  update-readme:
    needs: [check-version, build-and-release]
    if: needs.check-version.outputs.should_update == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update README version
        run: |
          # Update README with latest version
          sed -i "s/Latest version: .*/Latest version: ${{ needs.check-version.outputs.x64_version }}/g" README.md
          
          # Configure git
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Commit and push the changes
          git add README.md
          git commit -m "Update version to ${{ needs.check-version.outputs.x64_version }}"
          git push 