name: Placeholder
on:
  workflow_dispatch:
    
# This workflow has been intentionally disabled
# Please follow the instructions in the README.md for generating Snap Store credentials

jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder Step
        run: echo "This workflow is disabled. Please follow the README instructions." 